stages:
  - test
  - documentation
variables:
  SCHEDULER_PARAMETERS: "-n 8 -t 00:15:00 -A hpc-prf-cifi -p normal"
  JULIA_MOD: "lang/JuliaHPC/1.10.4-foss-2022a-CUDA-11.7.0"
  XRT_MOD: "xilinx/xrt/2.16"
  CI: "yes"
default:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  tags:
    - slurm
  before_script:
    - module load $JULIA_MOD

test_with_native:
  stage: test
  script:
    - module load fpga $XRT_MOD
    - export XCL_EMULATION_MODE=sw_emu
    - julia --color=yes --project=. -e 'using Pkg; Pkg.build(verbose=true); Pkg.test(; coverage = false);'

test_with_buildin:
  stage: test
  script:
    - module load fpga xilinx/vitis/2024.1
    - export XCL_EMULATION_MODE=sw_emu
    - julia --color=yes --project=. -e 'using Pkg; Pkg.build(verbose=true); Pkg.test(; coverage = false);'

test_example_buildin:
  stage: test
  script:
    - module load fpga $XRT_MOD
    - export XCL_EMULATION_MODE=sw_emu
    - cd examples/stream
    - make all TARGET=sw_emu
    - julia --color=yes --project stream_fpga.jl


# Documentation
build-and-deploy:
  stage: documentation
  only:
    - main
    - pushes
    - tags
    - external_pull_requests
  script:
    - cd docs
    - julia --color=yes build_docs.jl
  allow_failure: false
