name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'

jobs:
  build:
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v2
      - name: Build and deploy
        run: |
          cd docs
          julia --color=yes --project=. -e 'using Pkg; Pkg.add(url="https://github.com/pc2/DocThemePC2.jl.git"); Pkg.build(verbose=true);'
          julia --color=yes build_docs.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
